### ISSUE TITLE
YORO API Error: Missing or imcompatible binary

### ISSUE THREAD

**Issue by tan199954** [jamesljlster/yoro#2]
Im using WSL2 manjaro-linux.
I install cmake, gcc, opencv with command: pacman -S cmake gcc opencv.
Then, I install python-pytorch-opt-cuda with command: pacman -S python-pytorch-opt-cuda
git clone https://github.com/jamesljlster/yoro.git
cd yoro
pip install -r requirements.txt
Last, I install yoro with command: pip install -v .
Yorov0.6 is installed successful.
but ImportError: libhdf5.so.200: cannot open shared object file: No such file or directory
Please, help me.

DESKTOP-F7DJQE7# **pip install -v .**
Using pip 22.2 from /usr/lib/python3.10/site-packages/pip (python 3.10)
Processing /root/yoro/yoro
  Running command python setup.py egg_info
  -- The CXX compiler identification is GNU 12.1.0
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found OpenCV: /usr (found version "4.6.0")
  -- Looking for C++ include pthread.h
  -- Looking for C++ include pthread.h - found
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
  -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
  -- Found Threads: TRUE
  -- Found CUDA: /opt/cuda (found version "11.7")
  -- The CUDA compiler identification is NVIDIA 11.7.64
  -- Detecting CUDA compiler ABI info
  -- Detecting CUDA compiler ABI info - done
  -- Check for working CUDA compiler: /opt/cuda/bin/nvcc - skipped
  -- Detecting CUDA compile features
  -- Detecting CUDA compile features - done
  -- Caffe2: CUDA detected: 11.7
  -- Caffe2: CUDA nvcc is: /opt/cuda/bin/nvcc
  -- Caffe2: CUDA toolkit directory: /opt/cuda
  -- Caffe2: Header version is: 11.7
  -- Found CUDNN: /usr/lib/libcudnn.so
  -- Found cuDNN: v8.4.1  (include: /usr/include, library: /usr/lib/libcudnn.so)
  -- /opt/cuda/lib64/libnvrtc.so shorthash is d833c4f3
  -- Automatic GPU detection failed. Building for common architectures.
  -- Autodetected CUDA architecture(s): 3.5;5.0;5.2;6.0;6.1;7.0;7.5;8.0;8.6;8.6+PTX
  -- Added CUDA NVCC flags for: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_86,code=compute_86
  CMake Warning at /usr/lib/python3.10/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
    static library kineto_LIBRARY-NOTFOUND not found.
  Call Stack (most recent call first):
    /usr/lib/python3.10/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
    cmake/deps.cmake:20 (find_package)
    CMakeLists.txt:60 (include)

  -- Found Torch: /usr/lib/libtorch.so
  -- Found Python: /usr/bin/python3.10 (found version "3.10.5") found components: Interpreter Development Development.Module Development.Embed
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /root/yoro/yoro/py_build
  [ 14%] Building CXX object yoro/api/CMakeFiles/yoro_api.dir/calc_ops.cpp.o
  [ 28%] Building CXX object yoro/api/CMakeFiles/yoro_api.dir/rbox.cpp.o
  [ 42%] Building CXX object yoro/api/CMakeFiles/yoro_api.dir/yoro_impl.cpp.o
  [ 57%] Building CXX object yoro/api/CMakeFiles/yoro_api.dir/yoro_api.cpp.o
  [ 71%] Linking CXX shared library libyoro_api.so
  [ 71%] Built target yoro_api
  [ 85%] Building CXX object yoro/api/CMakeFiles/yoro_api_pym.dir/yoro_api_pym.cxx.o
  [100%] Linking CXX shared library yoro_api_pym.so
  [100%] Built target yoro_api_pym
  Install the project...
  -- Install configuration: "Release"
  -- Installing: /root/yoro/yoro/py_build/../yoro/lib/yoro_api/libyoro_api.so.0.6.0
  -- Up-to-date: /root/yoro/yoro/py_build/../yoro/lib/yoro_api/libyoro_api.so.0.6
  -- Set runtime path of "../yoro/lib/yoro_api/libyoro_api.so.0.6.0" to "/usr/lib/python3.10/site-packages/torch/lib:/opt/cuda/lib64"
  -- Up-to-date: /root/yoro/yoro/py_build/../yoro/lib/yoro_api/libyoro_api.so
  -- Installing: /root/yoro/yoro/py_build/../yoro/lib/cmake/yoro_api/yoro_api-targets.cmake
  -- Installing: /root/yoro/yoro/py_build/../yoro/lib/cmake/yoro_api/yoro_api-targets-release.cmake
  -- Up-to-date: /root/yoro/yoro/py_build/../yoro/include/yoro_api/yoro_api.hpp
  -- Up-to-date: /root/yoro/yoro/py_build/../yoro/include/yoro_api/yoro_api_config.h
  -- Installing: /root/yoro/yoro/yoro/api/yoro_api_pym.so
  -- Set runtime path of "/root/yoro/yoro/yoro/api/yoro_api_pym.so" to "$ORIGIN/../../yoro/lib/yoro_api:/usr/lib/python3.10/site-packages/torch/lib:/opt/cuda/lib64"
  -- Installing: /root/yoro/yoro/py_build/../yoro/lib/cmake/yoro_api/yoro_api-config.cmake
  -- Installing: /root/yoro/yoro/py_build/../yoro/lib/cmake/yoro_api/yoro_api-version.cmake
  -- Installing: /root/yoro/yoro/py_build/../yoro/bin/anchor_cluster
  -- Installing: /root/yoro/yoro/py_build/../yoro/bin/backup_exporter
  -- Installing: /root/yoro/yoro/py_build/../yoro/bin/map_evaluator
  -- Installing: /root/yoro/yoro/py_build/../yoro/bin/pretrain_exporter
  -- Installing: /root/yoro/yoro/py_build/../yoro/bin/recaller
  -- Installing: /root/yoro/yoro/py_build/../yoro/bin/trainer
  running egg_info
  creating /tmp/pip-pip-egg-info-6dw0prjm/yoro.egg-info
  writing /tmp/pip-pip-egg-info-6dw0prjm/yoro.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-6dw0prjm/yoro.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-pip-egg-info-6dw0prjm/yoro.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-6dw0prjm/yoro.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-6dw0prjm/yoro.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-6dw0prjm/yoro.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-pip-egg-info-6dw0prjm/yoro.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in /usr/lib/python3.10/site-packages (from yoro==0.6.0) (1.12.0)
Requirement already satisfied: torchvision in /usr/lib/python3.10/site-packages (from yoro==0.6.0) (0.13.0)
Requirement already satisfied: numpy in /usr/lib/python3.10/site-packages (from yoro==0.6.0) (1.23.0)
Requirement already satisfied: pyyaml in /usr/lib/python3.10/site-packages (from yoro==0.6.0) (6.0)
Requirement already satisfied: tqdm in /usr/lib/python3.10/site-packages (from yoro==0.6.0) (4.64.0)
Requirement already satisfied: typing-extensions in /usr/lib/python3.10/site-packages (from torch->yoro==0.6.0) (4.2.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/lib/python3.10/site-packages (from torchvision->yoro==0.6.0) (9.2.0)
Requirement already satisfied: requests in /usr/lib/python3.10/site-packages (from torchvision->yoro==0.6.0) (2.27.1)
Requirement already satisfied: chardet>=3.0.2 in /usr/lib/python3.10/site-packages (from requests->torchvision->yoro==0.6.0) (4.0.0)
Requirement already satisfied: idna>=2.5 in /usr/lib/python3.10/site-packages (from requests->torchvision->yoro==0.6.0) (3.3)
Requirement already satisfied: urllib3>=1.21.1 in /usr/lib/python3.10/site-packages (from requests->torchvision->yoro==0.6.0) (1.26.9)
Building wheels for collected packages: yoro
  Running command python setup.py bdist_wheel
  -- Caffe2: CUDA detected: 11.7
  -- Caffe2: CUDA nvcc is: /opt/cuda/bin/nvcc
  -- Caffe2: CUDA toolkit directory: /opt/cuda
  -- Caffe2: Header version is: 11.7
  -- Found cuDNN: v8.4.1  (include: /usr/include, library: /usr/lib/libcudnn.so)
  -- /opt/cuda/lib64/libnvrtc.so shorthash is d833c4f3
  -- Automatic GPU detection failed. Building for common architectures.
  -- Autodetected CUDA architecture(s): 3.5;5.0;5.2;6.0;6.1;7.0;7.5;8.0;8.6;8.6+PTX
  -- Added CUDA NVCC flags for: -gencode;arch=compute_35,code=sm_35;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_52,code=sm_52;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_61,code=sm_61;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86;-gencode;arch=compute_86,code=compute_86
  CMake Warning at /usr/lib/python3.10/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
    static library kineto_LIBRARY-NOTFOUND not found.
  Call Stack (most recent call first):
    /usr/lib/python3.10/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
    cmake/deps.cmake:20 (find_package)
    CMakeLists.txt:60 (include)

  -- Configuring done
  -- Generating done
  -- Build files have been written to: /root/yoro/yoro/py_build
  Consolidate compiler generated dependencies of target yoro_api
  [ 71%] Built target yoro_api
  Consolidate compiler generated dependencies of target yoro_api_pym
  [100%] Built target yoro_api_pym
  Install the project...
  -- Install configuration: "Release"
  -- Up-to-date: /root/yoro/yoro/py_build/../yoro/lib/yoro_api/libyoro_api.so.0.6.0
  -- Up-to-date: /root/yoro/yoro/py_build/../yoro/lib/yoro_api/libyoro_api.so.0.6
  -- Up-to-date: /root/yoro/yoro/py_build/../yoro/lib/yoro_api/libyoro_api.so
  -- Up-to-date: /root/yoro/yoro/py_build/../yoro/lib/cmake/yoro_api/yoro_api-targets.cmake
  -- Up-to-date: /root/yoro/yoro/py_build/../yoro/lib/cmake/yoro_api/yoro_api-targets-release.cmake
  -- Up-to-date: /root/yoro/yoro/py_build/../yoro/include/yoro_api/yoro_api.hpp
  -- Up-to-date: /root/yoro/yoro/py_build/../yoro/include/yoro_api/yoro_api_config.h
  -- Up-to-date: /root/yoro/yoro/yoro/api/yoro_api_pym.so
  -- Up-to-date: /root/yoro/yoro/py_build/../yoro/lib/cmake/yoro_api/yoro_api-config.cmake
  -- Up-to-date: /root/yoro/yoro/py_build/../yoro/lib/cmake/yoro_api/yoro_api-version.cmake
  -- Up-to-date: /root/yoro/yoro/py_build/../yoro/bin/anchor_cluster
  -- Up-to-date: /root/yoro/yoro/py_build/../yoro/bin/backup_exporter
  -- Up-to-date: /root/yoro/yoro/py_build/../yoro/bin/map_evaluator
  -- Up-to-date: /root/yoro/yoro/py_build/../yoro/bin/pretrain_exporter
  -- Up-to-date: /root/yoro/yoro/py_build/../yoro/bin/recaller
  -- Up-to-date: /root/yoro/yoro/py_build/../yoro/bin/trainer
  running bdist_wheel
  running build
  running build_py
  copying yoro/api/yoro_api_pym.so -> build/lib/yoro/api
  copying yoro/lib/cmake/yoro_api/yoro_api-version.cmake -> build/lib/yoro/lib/cmake/yoro_api
  copying yoro/lib/cmake/yoro_api/yoro_api-targets.cmake -> build/lib/yoro/lib/cmake/yoro_api
  copying yoro/lib/cmake/yoro_api/yoro_api-config.cmake -> build/lib/yoro/lib/cmake/yoro_api
  copying yoro/lib/cmake/yoro_api/yoro_api-targets-release.cmake -> build/lib/yoro/lib/cmake/yoro_api
  copying yoro/lib/yoro_api/libyoro_api.so.0.6 -> build/lib/yoro/lib/yoro_api
  copying yoro/lib/yoro_api/libyoro_api.so -> build/lib/yoro/lib/yoro_api
  copying yoro/lib/yoro_api/libyoro_api.so.0.6.0 -> build/lib/yoro/lib/yoro_api
  running build_scripts
  copying and adjusting yoro/bin/anchor_cluster -> build/scripts-3.10
  copying and adjusting yoro/bin/backup_exporter -> build/scripts-3.10
  copying and adjusting yoro/bin/recaller -> build/scripts-3.10
  copying and adjusting yoro/bin/trainer -> build/scripts-3.10
  copying and adjusting yoro/bin/pretrain_exporter -> build/scripts-3.10
  copying and adjusting yoro/bin/map_evaluator -> build/scripts-3.10
  /usr/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
    warnings.warn(
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/yoro
  creating build/bdist.linux-x86_64/wheel/yoro/include
  creating build/bdist.linux-x86_64/wheel/yoro/include/yoro_api
  copying build/lib/yoro/include/yoro_api/yoro_api_config.h -> build/bdist.linux-x86_64/wheel/yoro/include/yoro_api
  copying build/lib/yoro/include/yoro_api/yoro_api.hpp -> build/bdist.linux-x86_64/wheel/yoro/include/yoro_api
  creating build/bdist.linux-x86_64/wheel/yoro/layers
  copying build/lib/yoro/layers/rotdetect_layers.py -> build/bdist.linux-x86_64/wheel/yoro/layers
  copying build/lib/yoro/layers/functional.py -> build/bdist.linux-x86_64/wheel/yoro/layers
  copying build/lib/yoro/layers/yoro_layers.py -> build/bdist.linux-x86_64/wheel/yoro/layers
  copying build/lib/yoro/layers/__init__.py -> build/bdist.linux-x86_64/wheel/yoro/layers
  creating build/bdist.linux-x86_64/wheel/yoro/backbones
  copying build/lib/yoro/backbones/resnet.py -> build/bdist.linux-x86_64/wheel/yoro/backbones
  creating build/bdist.linux-x86_64/wheel/yoro/backbones/darknet
  copying build/lib/yoro/backbones/darknet/models.py -> build/bdist.linux-x86_64/wheel/yoro/backbones/darknet
  copying build/lib/yoro/backbones/darknet/layers.py -> build/bdist.linux-x86_64/wheel/yoro/backbones/darknet
  creating build/bdist.linux-x86_64/wheel/yoro/backbones/darknet/config
  copying build/lib/yoro/backbones/darknet/config/yolov3-tiny.cfg -> build/bdist.linux-x86_64/wheel/yoro/backbones/darknet/config
  copying build/lib/yoro/backbones/darknet/config/yolov3.cfg -> build/bdist.linux-x86_64/wheel/yoro/backbones/darknet/config
  copying build/lib/yoro/backbones/darknet/config/yolov4-csp.cfg -> build/bdist.linux-x86_64/wheel/yoro/backbones/darknet/config
  copying build/lib/yoro/backbones/darknet/config/yolov4.cfg -> build/bdist.linux-x86_64/wheel/yoro/backbones/darknet/config
  copying build/lib/yoro/backbones/darknet/config/yolov4-tiny.cfg -> build/bdist.linux-x86_64/wheel/yoro/backbones/darknet/config
  copying build/lib/yoro/backbones/darknet/config/__init__.py -> build/bdist.linux-x86_64/wheel/yoro/backbones/darknet/config
  copying build/lib/yoro/backbones/darknet/config_parser.py -> build/bdist.linux-x86_64/wheel/yoro/backbones/darknet
  copying build/lib/yoro/backbones/darknet/__init__.py -> build/bdist.linux-x86_64/wheel/yoro/backbones/darknet
  copying build/lib/yoro/backbones/darknet/activation.py -> build/bdist.linux-x86_64/wheel/yoro/backbones/darknet
  copying build/lib/yoro/backbones/__init__.py -> build/bdist.linux-x86_64/wheel/yoro/backbones
  copying build/lib/yoro/datasets.py -> build/bdist.linux-x86_64/wheel/yoro
  creating build/bdist.linux-x86_64/wheel/yoro/transforms
  copying build/lib/yoro/transforms/rbox.py -> build/bdist.linux-x86_64/wheel/yoro/transforms
  copying build/lib/yoro/transforms/rot.py -> build/bdist.linux-x86_64/wheel/yoro/transforms
  copying build/lib/yoro/transforms/__init__.py -> build/bdist.linux-x86_64/wheel/yoro/transforms
  creating build/bdist.linux-x86_64/wheel/yoro/lib
  creating build/bdist.linux-x86_64/wheel/yoro/lib/cmake
  creating build/bdist.linux-x86_64/wheel/yoro/lib/cmake/yoro_api
  copying build/lib/yoro/lib/cmake/yoro_api/yoro_api-version.cmake -> build/bdist.linux-x86_64/wheel/yoro/lib/cmake/yoro_api
  copying build/lib/yoro/lib/cmake/yoro_api/yoro_api-targets.cmake -> build/bdist.linux-x86_64/wheel/yoro/lib/cmake/yoro_api
  copying build/lib/yoro/lib/cmake/yoro_api/yoro_api-config.cmake -> build/bdist.linux-x86_64/wheel/yoro/lib/cmake/yoro_api
  copying build/lib/yoro/lib/cmake/yoro_api/yoro_api-targets-release.cmake -> build/bdist.linux-x86_64/wheel/yoro/lib/cmake/yoro_api
  creating build/bdist.linux-x86_64/wheel/yoro/lib/yoro_api
  copying build/lib/yoro/lib/yoro_api/libyoro_api.so.0.6 -> build/bdist.linux-x86_64/wheel/yoro/lib/yoro_api
  copying build/lib/yoro/lib/yoro_api/libyoro_api.so -> build/bdist.linux-x86_64/wheel/yoro/lib/yoro_api
  copying build/lib/yoro/lib/yoro_api/libyoro_api.so.0.6.0 -> build/bdist.linux-x86_64/wheel/yoro/lib/yoro_api
  creating build/bdist.linux-x86_64/wheel/yoro/optim
  copying build/lib/yoro/optim/lr_scheduler.py -> build/bdist.linux-x86_64/wheel/yoro/optim
  copying build/lib/yoro/optim/__init__.py -> build/bdist.linux-x86_64/wheel/yoro/optim
  creating build/bdist.linux-x86_64/wheel/yoro/utils
  copying build/lib/yoro/utils/object_loader.py -> build/bdist.linux-x86_64/wheel/yoro/utils
  creating build/bdist.linux-x86_64/wheel/yoro/utils/data
  copying build/lib/yoro/utils/data/sampler.py -> build/bdist.linux-x86_64/wheel/yoro/utils/data
  copying build/lib/yoro/utils/data/__init__.py -> build/bdist.linux-x86_64/wheel/yoro/utils/data
  copying build/lib/yoro/utils/info_summarize.py -> build/bdist.linux-x86_64/wheel/yoro/utils
  creating build/bdist.linux-x86_64/wheel/yoro/utils/train_util
  copying build/lib/yoro/utils/train_util/rotdetect_train.py -> build/bdist.linux-x86_64/wheel/yoro/utils/train_util
  copying build/lib/yoro/utils/train_util/yoro_train.py -> build/bdist.linux-x86_64/wheel/yoro/utils/train_util
  copying build/lib/yoro/utils/train_util/base_train.py -> build/bdist.linux-x86_64/wheel/yoro/utils/train_util
  copying build/lib/yoro/utils/train_util/__init__.py -> build/bdist.linux-x86_64/wheel/yoro/utils/train_util
  copying build/lib/yoro/utils/__init__.py -> build/bdist.linux-x86_64/wheel/yoro/utils
  creating build/bdist.linux-x86_64/wheel/yoro/ops
  copying build/lib/yoro/ops/ciou_loss.py -> build/bdist.linux-x86_64/wheel/yoro/ops
  copying build/lib/yoro/ops/__init__.py -> build/bdist.linux-x86_64/wheel/yoro/ops
  copying build/lib/yoro/ops/nms.py -> build/bdist.linux-x86_64/wheel/yoro/ops
  copying build/lib/yoro/visual.py -> build/bdist.linux-x86_64/wheel/yoro
  copying build/lib/yoro/__init__.py -> build/bdist.linux-x86_64/wheel/yoro
  creating build/bdist.linux-x86_64/wheel/yoro/api
  copying build/lib/yoro/api/__init__.py -> build/bdist.linux-x86_64/wheel/yoro/api
  copying build/lib/yoro/api/yoro_api_pym.so -> build/bdist.linux-x86_64/wheel/yoro/api
  running install_egg_info
  running egg_info
  writing yoro.egg-info/PKG-INFO
  writing dependency_links to yoro.egg-info/dependency_links.txt
  writing requirements to yoro.egg-info/requires.txt
  writing top-level names to yoro.egg-info/top_level.txt
  reading manifest file 'yoro.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file 'yoro.egg-info/SOURCES.txt'
  Copying yoro.egg-info to build/bdist.linux-x86_64/wheel/yoro-0.6.0-py3.10.egg-info
  running install_scripts
  creating build/bdist.linux-x86_64/wheel/yoro-0.6.0.data
  creating build/bdist.linux-x86_64/wheel/yoro-0.6.0.data/scripts
  copying build/scripts-3.10/map_evaluator -> build/bdist.linux-x86_64/wheel/yoro-0.6.0.data/scripts
  copying build/scripts-3.10/recaller -> build/bdist.linux-x86_64/wheel/yoro-0.6.0.data/scripts
  copying build/scripts-3.10/backup_exporter -> build/bdist.linux-x86_64/wheel/yoro-0.6.0.data/scripts
  copying build/scripts-3.10/pretrain_exporter -> build/bdist.linux-x86_64/wheel/yoro-0.6.0.data/scripts
  copying build/scripts-3.10/anchor_cluster -> build/bdist.linux-x86_64/wheel/yoro-0.6.0.data/scripts
  copying build/scripts-3.10/trainer -> build/bdist.linux-x86_64/wheel/yoro-0.6.0.data/scripts
  changing mode of build/bdist.linux-x86_64/wheel/yoro-0.6.0.data/scripts/map_evaluator to 755
  changing mode of build/bdist.linux-x86_64/wheel/yoro-0.6.0.data/scripts/recaller to 755
  changing mode of build/bdist.linux-x86_64/wheel/yoro-0.6.0.data/scripts/backup_exporter to 755
  changing mode of build/bdist.linux-x86_64/wheel/yoro-0.6.0.data/scripts/pretrain_exporter to 755
  changing mode of build/bdist.linux-x86_64/wheel/yoro-0.6.0.data/scripts/anchor_cluster to 755
  changing mode of build/bdist.linux-x86_64/wheel/yoro-0.6.0.data/scripts/trainer to 755
  adding license file "LICENSE" (matched pattern "LICEN[CS]E*")
  creating build/bdist.linux-x86_64/wheel/yoro-0.6.0.dist-info/WHEEL
  creating '/tmp/pip-wheel-mm4357gg/yoro-0.6.0-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
  adding 'yoro/__init__.py'
  adding 'yoro/datasets.py'
  adding 'yoro/visual.py'
  adding 'yoro/api/__init__.py'
  adding 'yoro/api/yoro_api_pym.so'
  adding 'yoro/backbones/__init__.py'
  adding 'yoro/backbones/resnet.py'
  adding 'yoro/backbones/darknet/__init__.py'
  adding 'yoro/backbones/darknet/activation.py'
  adding 'yoro/backbones/darknet/config_parser.py'
  adding 'yoro/backbones/darknet/layers.py'
  adding 'yoro/backbones/darknet/models.py'
  adding 'yoro/backbones/darknet/config/__init__.py'
  adding 'yoro/backbones/darknet/config/yolov3-tiny.cfg'
  adding 'yoro/backbones/darknet/config/yolov3.cfg'
  adding 'yoro/backbones/darknet/config/yolov4-csp.cfg'
  adding 'yoro/backbones/darknet/config/yolov4-tiny.cfg'
  adding 'yoro/backbones/darknet/config/yolov4.cfg'
  adding 'yoro/include/yoro_api/yoro_api.hpp'
  adding 'yoro/include/yoro_api/yoro_api_config.h'
  adding 'yoro/layers/__init__.py'
  adding 'yoro/layers/functional.py'
  adding 'yoro/layers/rotdetect_layers.py'
  adding 'yoro/layers/yoro_layers.py'
  adding 'yoro/lib/cmake/yoro_api/yoro_api-config.cmake'
  adding 'yoro/lib/cmake/yoro_api/yoro_api-targets-release.cmake'
  adding 'yoro/lib/cmake/yoro_api/yoro_api-targets.cmake'
  adding 'yoro/lib/cmake/yoro_api/yoro_api-version.cmake'
  adding 'yoro/lib/yoro_api/libyoro_api.so'
  adding 'yoro/lib/yoro_api/libyoro_api.so.0.6'
  adding 'yoro/lib/yoro_api/libyoro_api.so.0.6.0'
  adding 'yoro/ops/__init__.py'
  adding 'yoro/ops/ciou_loss.py'
  adding 'yoro/ops/nms.py'
  adding 'yoro/optim/__init__.py'
  adding 'yoro/optim/lr_scheduler.py'
  adding 'yoro/transforms/__init__.py'
  adding 'yoro/transforms/rbox.py'
  adding 'yoro/transforms/rot.py'
  adding 'yoro/utils/__init__.py'
  adding 'yoro/utils/info_summarize.py'
  adding 'yoro/utils/object_loader.py'
  adding 'yoro/utils/data/__init__.py'
  adding 'yoro/utils/data/sampler.py'
  adding 'yoro/utils/train_util/__init__.py'
  adding 'yoro/utils/train_util/base_train.py'
  adding 'yoro/utils/train_util/rotdetect_train.py'
  adding 'yoro/utils/train_util/yoro_train.py'
  adding 'yoro-0.6.0.data/scripts/anchor_cluster'
  adding 'yoro-0.6.0.data/scripts/backup_exporter'
  adding 'yoro-0.6.0.data/scripts/map_evaluator'
  adding 'yoro-0.6.0.data/scripts/pretrain_exporter'
  adding 'yoro-0.6.0.data/scripts/recaller'
  adding 'yoro-0.6.0.data/scripts/trainer'
  adding 'yoro-0.6.0.dist-info/LICENSE'
  adding 'yoro-0.6.0.dist-info/METADATA'
  adding 'yoro-0.6.0.dist-info/WHEEL'
  adding 'yoro-0.6.0.dist-info/top_level.txt'
  adding 'yoro-0.6.0.dist-info/RECORD'
  removing build/bdist.linux-x86_64/wheel
  Building wheel for yoro (setup.py) ... done
  Created wheel for yoro: filename=yoro-0.6.0-py3-none-any.whl size=356340 sha256=3c1855f55298f004eabacf63db91c91011b985bbad265ac81988623380a9cdc8
  Stored in directory: /tmp/pip-ephem-wheel-cache-3rgp3a66/wheels/57/2b/d4/219e3609420c90b68a83e60dafe098b7b04d7a9491a4c83277
Successfully built yoro
Installing collected packages: yoro
Successfully installed yoro-0.6.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
DESKTOP-F7DJQE7# **python**
Python 3.10.5 (main, Jun  6 2022, 18:49:26) [GCC 12.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yoro
Traceback (most recent call last):
  File "/root/yoro/yoro/yoro/api/__init__.py", line 5, in <module>
    from .yoro_api_pym import *
**ImportError: libhdf5.so.200: cannot open shared object file: No such file or directory**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/yoro/yoro/yoro/__init__.py", line 1, in <module>
    from . import api, backbones, datasets, layers, ops, optim, transforms, utils, visual
  File "/root/yoro/yoro/yoro/api/__init__.py", line 7, in <module>
    raise AssertionError('YORO API Error: Missing or imcompatible binary')
**AssertionError: YORO API Error: Missing or imcompatible binary**
>>> exit()

DESKTOP-F7DJQE7# **pip list**
Package            Version
------------------ ---------
appdirs            1.4.4
CacheControl       0.12.6
certifi            2022.6.15
cffi               1.15.1
chardet            4.0.0
colorama           0.4.5
commonmark         0.9.1
cryptography       37.0.4
distlib            0.3.5
distro             1.7.0
docutils           0.19
future             0.18.2
html5lib           1.1
idna               3.3
jaraco.context     4.1.1
jaraco.functools   3.5.1
jaraco.text        3.8.1
lockfile           0.12.2
more-itertools     8.13.0
msgpack            1.0.3
namcap             3.3.1
npyscreen          4.10.5
nspektr            0.4.0
numpy              1.23.0
opencv-python      4.6.0.66
ordered-set        4.0.2
packaging          21.3
pacman-mirrors     4.23.2
pep517             0.12.0
Pillow             9.2.0
pip                22.2
platformdirs       2.5.1
ply                3.11
progress           1.6
pyalpm             0.10.6
pybind11           2.10.0
pycparser          2.21
pyelftools         0.28
Pygments           2.12.0
pyOpenSSL          22.0.0
pyparsing          3.0.9
pytoml             0.1.21
PyYAML             6.0
requests           2.27.1
resolvelib         0.8.1
retrying           1.3.3
rich               12.5.0
setuptools         61.3.1
six                1.16.0
TBB                0.2
tenacity           8.0.1
tomli              2.0.1
torch              1.12.0
torchvision        0.13.0
tqdm               4.64.0
trove-classifiers  2022.6.26
typing_extensions  4.2.0
urllib3            1.26.9
validate-pyproject 0.9
webencodings       0.5.1
wheel              0.37.1
yoro               0.6.0

**Comment by jameslai-dev** [comment]
Hi @tan199954,

Thanks for your report.  
Would you help me try if installing hdf5 package with pacman could resolve this error or not?  
hdf5 contains the missing libhdf5.so.200, but I'm not sure if it's installed in your environment or not.  
Ref: https://archlinux.org/packages/community/x86_64/hdf5/files/

**Comment by tan199954** [comment]
Oh ye, thank you very much.
I fixed some error, which similar to it with command: pacman -S hdf5 openmpi vtk  glew fmt
and
rm path/to/python/site-packages/torch/lib/libgomp.so.1
ln -s /usr/lib/libgomp.so.1 path/to/python/site-packages/torch/lib/libgomp.so.1

Tomorrow, i will try training yoroV0.6 with my custom dataset.
Thank you!

**Comment by jameslai-dev** [comment]
I'm glad it helped you.
I'm closing this issue since it's resolved!
Please feel free to open new issues if you meet any problems in the future.
Good luck on model training!
