### ISSUE TITLE
Compile and install the YORO package, Command '['cmake', '--build', '.', '--target', 'install', '--parallel', '24']' returned non-zero exit status 2.

### ISSUE THREAD

**Issue by ghost** [jamesljlster/yoro#3]
hi, Im using Ubuntu 20.04.
I install cmake, gcc, opencv with command.
i use python==3.6.13 version,
pytorch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0 cudatoolkit=10.2.
And 

> git clone https://github.com/jamesljlster/yoro.git 
is OK.

But i stucked in this code.

> cd yoro
> pip install -v .

Using pip 21.2.2 from /home/yjoh/.conda/envs/yoro/lib/python3.6/site-packages/pip (python 3.6)
Processing /home/yjoh/Desktop/code/08_yolo_angle/yoro
[33m  DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
   pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.[0m
    Running command python setup.py egg_info
    /home/yjoh/.local/lib/python3.6/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
      SetuptoolsDeprecationWarning,
    -- The CXX compiler identification is GNU 9.4.0
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/c++ - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Looking for C++ include pthread.h
    -- Looking for C++ include pthread.h - found
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
    -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE
    -- Found CUDA: /usr/local/cuda-11.5 (found version "11.5")
    -- Caffe2: CUDA detected: 11.5
    -- Caffe2: CUDA nvcc is: /usr/local/cuda-11.5/bin/nvcc
    -- Caffe2: CUDA toolkit directory: /usr/local/cuda-11.5
    -- Caffe2: Header version is: 11.5
    -- Found CUDNN: /usr/local/cuda-11.5/lib64/libcudnn.so
    -- Found cuDNN: v8.3.2  (include: /usr/local/cuda-11.5/include, library: /usr/local/cuda-11.5/lib64/libcudnn.so)
    -- Autodetected CUDA architecture(s):  8.6
    -- Added CUDA NVCC flags for: -gencode;arch=compute_86,code=sm_86
    -- MKL_ARCH: None, set to ` intel64` by default
    -- MKL_ROOT /home/yjoh/.conda/envs/yoro
    -- MKL_LINK: None, set to ` dynamic` by default
    -- MKL_INTERFACE_FULL: None, set to ` intel_ilp64` by default
    -- MKL_THREADING: None, set to ` intel_thread` by default
    -- MKL_MPI: None, set to ` intelmpi` by default
    -- Found Torch: /home/yjoh/.conda/envs/yoro/lib/python3.6/site-packages/torch/lib/libtorch.so
    -- Found Python: /home/yjoh/.conda/envs/yoro/bin/python3.6 (found version "3.6.13") found components: Interpreter Development Development.Module Development.Embed
    -- Configuring done
    CMake Warning at yoro/api/CMakeLists.txt:53 (add_library):
      Cannot generate a safe runtime search path for target yoro_api because
      there is a cycle in the constraint graph:

        dir 0 is [/usr/local/cuda-11.5/lib64/stubs]
        dir 1 is [/home/yjoh/.conda/envs/yoro/lib]
          dir 2 must precede it due to runtime library [libcufft.so.10]
        dir 2 is [/usr/local/cuda-11.5/lib64]
          dir 1 must precede it due to runtime library [libnvToolsExt.so.1]

      Some of these libraries may not be found correctly.

    CMake Warning at yoro/api/CMakeLists.txt:72 (add_library):
      Cannot generate a safe runtime search path for target yoro_api_pym because
      there is a cycle in the constraint graph:

        dir 0 is [/tmp/pip-req-build-yqbxlkh9/py_build/yoro/api]
        dir 1 is [/usr/local/cuda-11.5/lib64]
          dir 2 must precede it due to runtime library [libnvToolsExt.so.1]
        dir 2 is [/home/yjoh/.conda/envs/yoro/lib]
          dir 1 must precede it due to runtime library [libcufft.so.10]

      Some of these libraries may not be found correctly.

    CMake Warning at yoro/api/CMakeLists.txt:72 (add_library):
      Cannot generate a safe dependent library path for target yoro_api_pym
      because there is a cycle in the constraint graph:

        dir 0 is [/usr/local/cuda-11.5/lib64]
          dir 1 must precede it due to runtime library [libnvToolsExt.so.1]
        dir 1 is [/home/yjoh/.conda/envs/yoro/lib]
          dir 0 must precede it due to runtime library [libcufft.so.10]

      Some of these libraries may not be found correctly.

    -- Generating done
    -- Build files have been written to: /tmp/pip-req-build-yqbxlkh9/py_build
    [ 14%] Building CXX object yoro/api/CMakeFiles/yoro_api.dir/calc_ops.cpp.o
    [ 28%] Building CXX object yoro/api/CMakeFiles/yoro_api.dir/rbox.cpp.o
    [ 42%] Building CXX object yoro/api/CMakeFiles/yoro_api.dir/yoro_api.cpp.o
    [ 57%] Building CXX object yoro/api/CMakeFiles/yoro_api.dir/yoro_impl.cpp.o
    /tmp/pip-req-build-yqbxlkh9/yoro/api/calc_ops.cpp: In function ‘std::tuple<at::Tensor, std::vector<long int, std::allocator<long int> > > yoro_api::pad_to_aspect(const at::Tensor&, float)’:
    /tmp/pip-req-build-yqbxlkh9/yoro/api/calc_ops.cpp:88:20: error: ‘bitwise_right_shift’ was not declared in this scope
       88 |     Tensor ltPad = bitwise_right_shift(sizeDiff, 1);
          |                    ^~~~~~~~~~~~~~~~~~~
    make[2]: *** [yoro/api/CMakeFiles/yoro_api.dir/build.make:76: yoro/api/CMakeFiles/yoro_api.dir/calc_ops.cpp.o] Error 1
    make[2]: *** Waiting for unfinished jobs....
    make[1]: *** [CMakeFiles/Makefile2:118: yoro/api/CMakeFiles/yoro_api.dir/all] Error 2
    make: *** [Makefile:136: all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-yqbxlkh9/setup.py", line 92, in <module>
        build_yoro_api()
      File "/tmp/pip-req-build-yqbxlkh9/setup.py", line 80, in build_yoro_api
        extra_ldpath=[join(torchPath, 'lib')]
      File "/tmp/pip-req-build-yqbxlkh9/setup.py", line 58, in __init__
        ], cwd=buildDir)
      File "/home/yjoh/.conda/envs/yoro/lib/python3.6/subprocess.py", line 311, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--parallel', '24']' returned non-zero exit status 2.
[33mWARNING: Discarding file:///home/yjoh/Desktop/code/08_yolo_angle/yoro. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.[0m
[31mERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.[0m

if you know how fix it? Thank you.

**Comment by jameslai-dev** [comment]
Hi yjoh,

I installed PyTorch 1.7.0 and realized that it does not support `bitwise_right_shift` operator.
Would you like to try installing newer PyTorch?
I recommend 1.11 the most, which I use in my development environment currently.
If you meet any problem in the future, please don't hesitate to ask me.

**Comment by ghost** [comment]
yes, it works! 
I didn't know that pytorch version's error.
It helped me a lot thank you.
