### ISSUE TITLE
anaconda3/lib/libmkl_intel_thread.so: undefined symbol: __kmpc_reduce_nowait

### ISSUE THREAD

**Issue by ghost** [jamesljlster/yoro#4]
hi, i'm studying your code.

`!cd {YORO_DIR} &&pip install -v .`
there are warnings but ended with "Successfully installed yoro-0.6.0".

so i thought the installation went well.

`import yoro`

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~/.conda/envs/yoro2/lib/python3.7/site-packages/yoro/api/__init__.py in <module>
      4 try:
----> 5     from .yoro_api_pym import *
      6 except :

**ImportError: /home/yjoh/anaconda3/lib/libmkl_intel_thread.so: undefined symbol: __kmpc_reduce_nowait**

During handling of the above exception, another exception occurred:

AssertionError                            Traceback (most recent call last)
/tmp/ipykernel_15114/415478366.py in <module>
----> 1 import yoro

~/.conda/envs/yoro2/lib/python3.7/site-packages/yoro/__init__.py in <module>
----> 1 from . import api, backbones, datasets, layers, ops, optim, transforms, utils, visual

~/.conda/envs/yoro2/lib/python3.7/site-packages/yoro/api/__init__.py in <module>
      6 except :
      7     # raise AssertionError(e)
----> 8     raise AssertionError('YORO API Error: Missing or imcompatible binary')
      9 
     10 

**AssertionError: YORO API Error: Missing or imcompatible binary**

--------------------------------------------------------------------------------------------------------------
my environment

ubuntu 20.04 LTS

i used anaconda env
python : 3.8.15
pytorch : 1.11.0
orchvision : 0.12.0
cudatoolkit : 10.2
numpy : 1.21.5
ninja : 1.11.1
pyyaml : 6.0
mkl :2022.2.1
mkl-include : 2022.2.1
future : 0.18.2
dataclasses : 0.6
intel-openmp : 2022.2.1
tbb : 2021.7.1

--------------------------------------------------------------------------------------------------------------

I tried to fix it myself but it didn't work.
Do you know anything about this issue?

+) this is my yoro package install output.

Using pip 22.2.2 from /home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages/pip (python 3.8)
Obtaining file:///home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro
  Running command python setup.py egg_info
  -- Caffe2: CUDA detected: 11.5
  -- Caffe2: CUDA nvcc is: /usr/local/cuda-11.5/bin/nvcc
  -- Caffe2: CUDA toolkit directory: /usr/local/cuda-11.5
  -- Caffe2: Header version is: 11.5
  -- Found cuDNN: v8.3.2  (include: /usr/local/cuda-11.5/include, library: /usr/local/cuda-11.5/lib64/libcudnn.so)
  -- /home/yjoh/.conda/envs/yoro/lib/libnvrtc.so shorthash is 5a908bce
  -- Autodetected CUDA architecture(s):  8.6
  -- Added CUDA NVCC flags for: -gencode;arch=compute_86,code=sm_86
  -- MKL_ARCH: intel64
  -- MKL_ROOT /home/yjoh/.conda/envs/yoro
  -- MKL_LINK: dynamic
  -- MKL_INTERFACE_FULL: intel_ilp64
  -- MKL_THREADING: intel_thread
  -- MKL_MPI: intelmpi
  CMake Warning at /home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
    static library kineto_LIBRARY-NOTFOUND not found.
  Call Stack (most recent call first):
    /home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
    cmake/deps.cmake:20 (find_package)
    CMakeLists.txt:59 (include)

  -- Found Torch: /home/yjoh/.conda/envs/yoro/lib/python3.8/site-packages/torch/lib/libtorch.so
  -- Found Python: /home/yjoh/.conda/envs/drbox/bin/python3.8 (found version "3.8.15") found components: Interpreter Development Development.Module Development.Embed
  -- Configuring done
  CMake Warning at yoro/api/CMakeLists.txt:53 (add_library):
    Cannot generate a safe runtime search path for target yoro_api because
    files in some directories may conflict with libraries in implicit
    directories:

      runtime library [libc10.so] in /home/yjoh/.conda/envs/yoro/lib/python3.8/site-packages/torch/lib may be hidden by files in:
        /home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages/torch/lib
      runtime library [libc10_cuda.so] in /home/yjoh/.conda/envs/yoro/lib/python3.8/site-packages/torch/lib may be hidden by files in:
        /home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages/torch/lib

    Some of these libraries may not be found correctly.

  CMake Warning at yoro/api/CMakeLists.txt:53 (add_library):
    Cannot generate a safe runtime search path for target yoro_api because
    there is a cycle in the constraint graph:

      dir 0 is [/home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages/torch/lib]
      dir 1 is [/usr/local/cuda-11.5/lib64/stubs]
      dir 2 is [/home/yjoh/.conda/envs/yoro/lib]
        dir 3 must precede it due to runtime library [libcufft.so.10]
      dir 3 is [/usr/local/cuda-11.5/lib64]
        dir 2 must precede it due to runtime library [libnvToolsExt.so.1]

    Some of these libraries may not be found correctly.

  CMake Warning at yoro/api/CMakeLists.txt:72 (add_library):
    Cannot generate a safe runtime search path for target yoro_api_pym because
    there is a cycle in the constraint graph:

      dir 0 is [/home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages/torch/lib]
      dir 1 is [/home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/yoro/api]
      dir 2 is [/usr/local/cuda-11.5/lib64]
        dir 3 must precede it due to runtime library [libnvToolsExt.so.1]
      dir 3 is [/home/yjoh/.conda/envs/yoro/lib]
        dir 2 must precede it due to runtime library [libcufft.so.10]

    Some of these libraries may not be found correctly.

  CMake Warning at yoro/api/CMakeLists.txt:72 (add_library):
    Cannot generate a safe dependent library path for target yoro_api_pym
    because there is a cycle in the constraint graph:

      dir 0 is [/home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages/torch/lib]
      dir 1 is [/usr/local/cuda-11.5/lib64]
        dir 2 must precede it due to runtime library [libnvToolsExt.so.1]
      dir 2 is [/home/yjoh/.conda/envs/yoro/lib]
        dir 1 must precede it due to runtime library [libcufft.so.10]

    Some of these libraries may not be found correctly.

  -- Generating done
  -- Build files have been written to: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build
  Consolidate compiler generated dependencies of target yoro_api
  [ 28%] Building CXX object yoro/api/CMakeFiles/yoro_api.dir/calc_ops.cpp.o
  [ 28%] Building CXX object yoro/api/CMakeFiles/yoro_api.dir/rbox.cpp.o
  [ 42%] Building CXX object yoro/api/CMakeFiles/yoro_api.dir/yoro_api.cpp.o
  [ 57%] Building CXX object yoro/api/CMakeFiles/yoro_api.dir/yoro_impl.cpp.o
  [ 71%] Linking CXX shared library libyoro_api.so
  [ 71%] Built target yoro_api
  Consolidate compiler generated dependencies of target yoro_api_pym
  [ 85%] Building CXX object yoro/api/CMakeFiles/yoro_api_pym.dir/yoro_api_pym.cxx.o
  [100%] Linking CXX shared library yoro_api_pym.so
  [100%] Built target yoro_api_pym
  Install the project...
  -- Install configuration: "Release"
  -- Installing: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/lib/yoro_api/libyoro_api.so.0.6.0
  -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/lib/yoro_api/libyoro_api.so.0.6
  -- Set runtime path of "../yoro/lib/yoro_api/libyoro_api.so.0.6.0" to "/home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages/torch/lib:/usr/local/cuda-11.5/lib64/stubs:/usr/local/cuda-11.5/lib64:/home/yjoh/.conda/envs/yoro/lib"
  -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/lib/yoro_api/libyoro_api.so
  -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/lib/cmake/yoro_api/yoro_api-targets.cmake
  -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/lib/cmake/yoro_api/yoro_api-targets-release.cmake
  -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/include/yoro_api/yoro_api.hpp
  -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/include/yoro_api/yoro_api_config.h
  -- Installing: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/yoro/api/yoro_api_pym.so
  -- Set runtime path of "/home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/yoro/api/yoro_api_pym.so" to "$ORIGIN/../../yoro/lib/yoro_api:/home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages/torch/lib:/home/yjoh/.conda/envs/yoro/lib:/usr/local/cuda-11.5/lib64"
  -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/lib/cmake/yoro_api/yoro_api-config.cmake
  -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/lib/cmake/yoro_api/yoro_api-version.cmake
  -- Installing: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/bin/anchor_cluster
  -- Installing: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/bin/backup_exporter
  -- Installing: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/bin/map_evaluator
  -- Installing: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/bin/pretrain_exporter
  -- Installing: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/bin/recaller
  -- Installing: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/bin/trainer
  running egg_info
  creating /tmp/pip-pip-egg-info-fm20tbwh/yoro.egg-info
  writing /tmp/pip-pip-egg-info-fm20tbwh/yoro.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-fm20tbwh/yoro.egg-info/dependency_links.txt
  writing requirements to /tmp/pip-pip-egg-info-fm20tbwh/yoro.egg-info/requires.txt
  writing top-level names to /tmp/pip-pip-egg-info-fm20tbwh/yoro.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-fm20tbwh/yoro.egg-info/SOURCES.txt'
  reading manifest file '/tmp/pip-pip-egg-info-fm20tbwh/yoro.egg-info/SOURCES.txt'
  adding license file 'LICENSE'
  writing manifest file '/tmp/pip-pip-egg-info-fm20tbwh/yoro.egg-info/SOURCES.txt'
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch in /home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages (from yoro==0.6.0) (1.10.1+cu113)
Requirement already satisfied: torchvision in /home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages (from yoro==0.6.0) (0.11.2+cu113)
Requirement already satisfied: numpy in /home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages (from yoro==0.6.0) (1.23.5)
Collecting pyyaml
  Using cached PyYAML-6.0-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (701 kB)
Collecting tqdm
  Using cached tqdm-4.64.1-py2.py3-none-any.whl (78 kB)
Requirement already satisfied: typing-extensions in /home/yjoh/.local/lib/python3.8/site-packages (from torch->yoro==0.6.0) (4.4.0)
Requirement already satisfied: pillow!=8.3.0,>=5.3.0 in /home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages (from torchvision->yoro==0.6.0) (9.3.0)
Installing collected packages: tqdm, pyyaml, yoro
  changing mode of /home/yjoh/.conda/envs/drbox/bin/tqdm to 775
  Running setup.py develop for yoro
    Running command python setup.py develop
    -- Caffe2: CUDA detected: 11.5
    -- Caffe2: CUDA nvcc is: /usr/local/cuda-11.5/bin/nvcc
    -- Caffe2: CUDA toolkit directory: /usr/local/cuda-11.5
    -- Caffe2: Header version is: 11.5
    -- Found cuDNN: v8.3.2  (include: /usr/local/cuda-11.5/include, library: /usr/local/cuda-11.5/lib64/libcudnn.so)
    -- /home/yjoh/.conda/envs/yoro/lib/libnvrtc.so shorthash is 5a908bce
    -- Autodetected CUDA architecture(s):  8.6
    -- Added CUDA NVCC flags for: -gencode;arch=compute_86,code=sm_86
    -- MKL_ARCH: intel64
    -- MKL_ROOT /home/yjoh/.conda/envs/yoro
    -- MKL_LINK: dynamic
    -- MKL_INTERFACE_FULL: intel_ilp64
    -- MKL_THREADING: intel_thread
    -- MKL_MPI: intelmpi
    CMake Warning at /home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:22 (message):
      static library kineto_LIBRARY-NOTFOUND not found.
    Call Stack (most recent call first):
      /home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:127 (append_torchlib_if_found)
      cmake/deps.cmake:20 (find_package)
      CMakeLists.txt:59 (include)

    -- Configuring done
    CMake Warning at yoro/api/CMakeLists.txt:53 (add_library):
      Cannot generate a safe runtime search path for target yoro_api because
      files in some directories may conflict with libraries in implicit
      directories:

        runtime library [libc10.so] in /home/yjoh/.conda/envs/yoro/lib/python3.8/site-packages/torch/lib may be hidden by files in:
          /home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages/torch/lib
        runtime library [libc10_cuda.so] in /home/yjoh/.conda/envs/yoro/lib/python3.8/site-packages/torch/lib may be hidden by files in:
          /home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages/torch/lib

      Some of these libraries may not be found correctly.

    CMake Warning at yoro/api/CMakeLists.txt:53 (add_library):
      Cannot generate a safe runtime search path for target yoro_api because
      there is a cycle in the constraint graph:

        dir 0 is [/home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages/torch/lib]
        dir 1 is [/usr/local/cuda-11.5/lib64/stubs]
        dir 2 is [/home/yjoh/.conda/envs/yoro/lib]
          dir 3 must precede it due to runtime library [libcufft.so.10]
        dir 3 is [/usr/local/cuda-11.5/lib64]
          dir 2 must precede it due to runtime library [libnvToolsExt.so.1]

      Some of these libraries may not be found correctly.

    CMake Warning at yoro/api/CMakeLists.txt:72 (add_library):
      Cannot generate a safe runtime search path for target yoro_api_pym because
      there is a cycle in the constraint graph:

        dir 0 is [/home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages/torch/lib]
        dir 1 is [/home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/yoro/api]
        dir 2 is [/usr/local/cuda-11.5/lib64]
          dir 3 must precede it due to runtime library [libnvToolsExt.so.1]
        dir 3 is [/home/yjoh/.conda/envs/yoro/lib]
          dir 2 must precede it due to runtime library [libcufft.so.10]

      Some of these libraries may not be found correctly.

    CMake Warning at yoro/api/CMakeLists.txt:72 (add_library):
      Cannot generate a safe dependent library path for target yoro_api_pym
      because there is a cycle in the constraint graph:

        dir 0 is [/home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages/torch/lib]
        dir 1 is [/usr/local/cuda-11.5/lib64]
          dir 2 must precede it due to runtime library [libnvToolsExt.so.1]
        dir 2 is [/home/yjoh/.conda/envs/yoro/lib]
          dir 1 must precede it due to runtime library [libcufft.so.10]

      Some of these libraries may not be found correctly.

    -- Generating done
    -- Build files have been written to: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build
    Consolidate compiler generated dependencies of target yoro_api
    [ 71%] Built target yoro_api
    Consolidate compiler generated dependencies of target yoro_api_pym
    [100%] Built target yoro_api_pym
    Install the project...
    -- Install configuration: "Release"
    -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/lib/yoro_api/libyoro_api.so.0.6.0
    -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/lib/yoro_api/libyoro_api.so.0.6
    -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/lib/yoro_api/libyoro_api.so
    -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/lib/cmake/yoro_api/yoro_api-targets.cmake
    -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/lib/cmake/yoro_api/yoro_api-targets-release.cmake
    -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/include/yoro_api/yoro_api.hpp
    -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/include/yoro_api/yoro_api_config.h
    -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/yoro/api/yoro_api_pym.so
    -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/lib/cmake/yoro_api/yoro_api-config.cmake
    -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/lib/cmake/yoro_api/yoro_api-version.cmake
    -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/bin/anchor_cluster
    -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/bin/backup_exporter
    -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/bin/map_evaluator
    -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/bin/pretrain_exporter
    -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/bin/recaller
    -- Up-to-date: /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro/py_build/../yoro/bin/trainer
    running develop
    running egg_info
    writing yoro.egg-info/PKG-INFO
    writing dependency_links to yoro.egg-info/dependency_links.txt
    writing requirements to yoro.egg-info/requires.txt
    writing top-level names to yoro.egg-info/top_level.txt
    reading manifest file 'yoro.egg-info/SOURCES.txt'
    adding license file 'LICENSE'
    writing manifest file 'yoro.egg-info/SOURCES.txt'
    running build_ext
    Creating /home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages/yoro.egg-link (link to .)
    Adding yoro 0.6.0 to easy-install.pth file
    Installing anchor_cluster script to /home/yjoh/.conda/envs/drbox/bin
    Installing backup_exporter script to /home/yjoh/.conda/envs/drbox/bin
    Installing recaller script to /home/yjoh/.conda/envs/drbox/bin
    Installing trainer script to /home/yjoh/.conda/envs/drbox/bin
    Installing pretrain_exporter script to /home/yjoh/.conda/envs/drbox/bin
    Installing map_evaluator script to /home/yjoh/.conda/envs/drbox/bin

    Installed /home/yjoh/Desktop/code/08_yolo_angle/221205_retry/yoro
    /home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages/setuptools/command/easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /home/yjoh/.conda/envs/drbox/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
Successfully installed pyyaml-6.0 tqdm-4.64.1 yoro-0.6.0

**Comment by jameslai-dev** [comment]
Hi @yjoh-autonics,

It seems your environment is a little bit too much complicated XD
Please try the following instructions to create a fresh conda environment for YORO:

```sh
# Create and activate a fresh conda environment
conda create -n yoro-env python==3.8.15
conda activate yoro-env  # This conda environment should be kept activated for the rest of instructions

# Install PyTorch 1.11.0 and corresponding CUDA Toolkit
conda install pytorch==1.11.0 torchvision==0.12.0 torchaudio==0.11.0 cudatoolkit=11.3 -c pytorch
conda install -c "nvidia/label/cuda-11.3.1" cuda-toolkit

# Install some build dependendies (cmake, gcc)
conda install -c conda-forge "gxx_linux-64<11"
conda install -c anaconda cmake

# Build and install YORO package
git clone https://github.com/jamesljlster/yoro.git
cd yoro
pip install -v .
cd ..

# Test if everything is fine
python -c "import yoro"
```

**Comment by ghost** [comment]
Thank you. it is works!

Just one more question,

i put config.yaml
  deg_min: -180
  deg_max: 180

so i expect total 360 degree output.

But i input below image.
i expect minus degree like -176.6 but it's output is degree: 3.32289.
[conf: 0.998593, label: 0, degree: 3.32289, x: 377.3, y: 141.65, w: 122.074, h: 121]

![test](https://user-images.githubusercontent.com/112674993/207491171-478b56d9-b096-416d-b8ba-8abf88e5e2f0.jpg)
![image](https://user-images.githubusercontent.com/112674993/207492756-3c9a91f8-4e03-496b-9682-46b4e2133c0b.png)
![image](https://user-images.githubusercontent.com/112674993/207532681-19e5a76f-5ae7-4691-8826-a6a329804129.png)


Can't yoro find the 360 ​​degree rotation angle or is there something I need to change in the config settings?
I'm really appreciate your help!

**Comment by jameslai-dev** [comment]
Hi @yjoh-autonics,

That's a great question!
Your setting is correct.
However, the config.yaml just defines the model capability, the model ability is learned from dataset.
The degree range of the demo dataset (coating) is around [-63.58, 52.12], so the demo model's rotation recognition ability is about in the same range.
If you want a model that can have wider degree recognition range, you must train it with corresponding dataset.
Although augmentation can help a lot, it's always nice to have real samples in the dataset to help model training.
If you have any future question, please feel free to ask me.

**Comment by ghost** [comment]
I will try new data! Thank you :)
