### ISSUE TITLE
custom data training error

### ISSUE THREAD

**Issue by ghost** [jamesljlster/yoro#5]
hi, i'm here XD.

i want to train my data.
so i change config , just dataset part (file path) on example.yaml in your configs.
( anchor is not change, because you said it is also okay to skip.)

And my dataset have 62 classes and more than 20 detections per picture.
And train dataset are 2,207.

dataset structure is same.
data
   - train
      - data.jpg
      - data.jpg.mark
   - valid
   - data.names

my train error code is below.
Do you konw why it have IndexError?
Thank you for your help.

-----

=== Validation on Iter 0 ===
  0%|                                                     | 0/1 [00:00<?, ?it/s]/home/yjoh/anaconda3/envs/yoro-env/lib/python3.8/site-packages/yoro/transforms/rbox.py:356: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755903507/work/torch/csrc/utils/tensor_new.cpp:210.)
  [torch.tensor(elem, dtype=dtype) for (elem, dtype) in
Traceback (most recent call last):                                              
  File "/home/yjoh/anaconda3/envs/yoro-env/bin/trainer", line 69, in <module>
    tc.valid()
  File "/home/yjoh/anaconda3/envs/yoro-env/lib/python3.8/site-packages/yoro/utils/train_util/base_train.py", line 255, in valid
    for inst in loop:
  File "/home/yjoh/anaconda3/envs/yoro-env/lib/python3.8/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/yjoh/anaconda3/envs/yoro-env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/yjoh/anaconda3/envs/yoro-env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/yjoh/anaconda3/envs/yoro-env/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/yjoh/anaconda3/envs/yoro-env/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yjoh/anaconda3/envs/yoro-env/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yjoh/anaconda3/envs/yoro-env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yjoh/anaconda3/envs/yoro-env/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yjoh/anaconda3/envs/yoro-env/lib/python3.8/site-packages/yoro/datasets.py", line 96, in __getitem__
    sample = self.transform(sample)
  File "/home/yjoh/anaconda3/envs/yoro-env/lib/python3.8/site-packages/torchvision/transforms/transforms.py", line 95, in __call__
    img = t(img)
  File "/home/yjoh/anaconda3/envs/yoro-env/lib/python3.8/site-packages/yoro/transforms/rbox.py", line 423, in __call__
    anno = self.tgtBuilder(anno)
  File "/home/yjoh/anaconda3/envs/yoro-env/lib/python3.8/site-packages/yoro/transforms/rbox.py", line 313, in __call__
    if not objs[headIdx][acrIdx, yIdx, xIdx]:
IndexError: index 7 is out of bounds for dimension 1 with size 7

-----

example)
data.jpg.mark
- degree: 0.0
  h: 32.5
  label: 50
  w: 36.1400000000001
  x: 990.13
  y: 146.45
- degree: -7.000000333982996
  h: 69.54999999999995
  label: 0
  w: 44.129999999999995
  x: 556.655
  y: 613.265
- degree: 0.0
  h: 33.379999999999995
  label: 56
  w: 32.41999999999996
  x: 1025.79
  y: 146.91
- degree: -9.399999999999977
  h: 84.32
  label: 3
  w: 48.200000000000045
  x: 1069.08
  y: 130.56
- degree: 0.0
  h: 32.47999999999999
  label: 40
  w: 32.39999999999998
  x: 870.0999999999999
  y: 148.26
.....

data.names
- 0
- 1
- ....
- 61

**Comment by jameslai-dev** [comment]
Hi @yjoh-autonics,

Glad to see you again! XD

The error indicates that `yIdx` is out of bound.
Maybe there are some problems in your dataset annotations.
Would you help me run the following script to check your dataset?

``` python
from tqdm import tqdm
from yoro.datasets import RBoxSample

# Load dataset
dataset = RBoxSample(
    image_dir='~/dataset/coating/valid',
    names_file='~/dataset/coating/coating.names'
)

# Check for annotations
for sample_idx, (image, anno) in enumerate(tqdm(dataset, desc='Checking annotation')):
    for idx, inst in enumerate(anno):
        valid = (
            (inst['x'] >= 0 and inst['x'] < image.width) and
            (inst['y'] >= 0 and inst['y'] < image.height)
        )
        if not valid:
            image_path = dataset.instList[idx]['file']
            print(f'Annotation {idx} is not valid for image {image_path}')
```

And please don't forget to replace `image_dir` and `names_file` according to your dataset location.

Also, you may give [yolov4-tiny.yaml](https://github.com/jamesljlster/yoro/blob/master/config/yolov4-tiny.yaml) a try.
It would have better performance.

**Comment by ghost** [comment]
In the result of returning to the code you gave, there are strange data.
I don't know why those data appeared.
inst means my mark data?
but it has difference in mine.
Do you have any code to convert the data?

example)
`from tqdm import tqdm
from yoro.datasets import RBoxSample

- Load dataset
dataset = RBoxSample(
    image_dir='/home/yjoh/Desktop/code/08_yolo_angle/221214_yoro/dataset/custom/train',
    names_file='/home/yjoh/Desktop/code/08_yolo_angle/221214_yoro/dataset/custom/custom.names'
)

- Check for annotations
for sample_idx, (image, anno) in enumerate(tqdm(dataset, desc='Checking annotation')):
    for idx, inst in enumerate(anno):
        valid = (
            (inst['x'] >= 0 and inst['x'] < image.width) and
            (inst['y'] >= 0 and inst['y'] < image.height)
        )
        if not valid:
            print('here')
            print(inst)
            print('image.width, image.height')
            print(image.width, image.height)
            print("inst['x'],inst['y']")
            print(inst['x'],inst['y'])
            print((inst['x'] >= 0 and inst['x'] < image.width))
            print((inst['y'] >= 0 and inst['y'] < image.height))

            image_path = dataset.instList[idx]['file']
            print(f'Annotation {idx} is not valid for image {image_path}')`

out:
here
{'degree': 34.5, 'h': 76.17999999999995, 'label': 61, 'w': 65.35000000000014, 'x': 1246.295, 'y': 723.81}
image.width, image.height
1280 720
inst['x'],inst['y']
1246.295 723.81
True
False
Annotation 6 is not valid for image /home/yjoh/Desktop/code/08_yolo_angle/221214_yoro/dataset/custom/train/data-1000.jpg

my data all (data-1000.jpg.mark):
- degree: -4.0
  h: 66.41
  label: 25
  w: 45.910000000000025
  x: 430.345
  y: 126.105
- degree: -3.1999999999999886
  h: 70.00000000000001
  label: 6
  w: 48.15999999999997
  x: 301.51
  y: 136.83
- degree: -5.899999999999977
  h: 70.0
  label: 0
  w: 48.370000000000005
  x: 615.2249999999999
  y: 630.24
- degree: -4.100000000000023
  h: 73.27999999999997
  label: 0
  w: 51.379999999999995
  x: 853.81
  y: 436.01
- degree: -3.8000000000000114
  h: 66.2
  label: 27
  w: 46.579999999999984
  x: 366.22
  y: 133.08
- degree: -3.5
  h: 66.20000000000002
  label: 27
  w: 52.400000000000034
  x: 375.23
  y: 228.01
- degree: -4.300000000000011
  h: 71.0
  label: 2
  w: 50.0
  x: 314.0
  y: 232.5
- degree: -3.5
  h: 72.0
  label: 1
  w: 38.89999999999998
  x: 509.45
  y: 297.12
- degree: -4.699999999999989
  h: 73.0
  label: 5
  w: 50.0
  x: 833.0
  y: 259.5
- degree: -4.699999999999989
  h: 72.67
  label: 0
  w: 52.89999999999998
  x: 556.77
  y: 108.565
- degree: -5.5
  h: 67.0
  label: 11
  w: 51.14999999999998
  x: 458.745
  y: 398.36
- degree: -5.100000000000023
  h: 74.89999999999998
  label: 0
  w: 51.299999999999955
  x: 644.34
  y: 283.25
- degree: -4.399999999999977
  h: 72.0
  label: 8
  w: 53.0
  x: 769.5
  y: 270.0
- degree: -3.8999999999999773
  h: 73.0
  label: 0
  w: 54.89999999999998
  x: 706.55
  y: 276.43
- degree: -3.1000000000000227
  h: 69.0
  label: 11
  w: 54.0
  x: 893.0
  y: 256.55
- degree: -3.6000000000000227
  h: 67.0
  label: 12
  w: 45.400000000000034
  x: 395.78
  y: 406.94
- degree: -4.199999999999989
  h: 67.0
  label: 11
  w: 51.85000000000002
  x: 804.9849999999999
  y: 611.17
- degree: -6.0
  h: 64.0
  label: 25
  w: 49.90999999999997
  x: 492.555
  y: 645.73
- degree: -5.600000000000023
  h: 69.0
  label: 9
  w: 50.0
  x: 678.0
  y: 622.5
- degree: -4.0
  h: 66.0
  label: 1
  w: 35.45999999999998
  x: 519.93
  y: 392.62
- degree: -4.699999999999989
  h: 72.0
  label: 4
  w: 50.0
  x: 778.0
  y: 360.0
- degree: -4.300000000000011
  h: 61.460000000000036
  label: 27
  w: 46.73000000000002
  x: 429.505
  y: 653.0
- degree: -3.0
  h: 67.59999999999991
  label: 7
  w: 51.400000000000034
  x: 364.71000000000004
  y: 657.24
- degree: -4.600000000000023
  h: 69.51999999999998
  label: 1
  w: 29.719999999999914
  x: 532.05
  y: 471.25
- degree: -4.399999999999977
  h: 72.09999999999991
  label: 1
  w: 42.0
  x: 550.0
  y: 635.99
- degree: -5.300000000000011
  h: 67.72
  label: 4
  w: 50.40999999999997
  x: 697.315
  y: 188.04000000000002
- degree: -3.8999999999999773
  h: 70.9
  label: 1
  w: 44.0
  x: 682.11
  y: 92.55
- degree: -4.699999999999989
  h: 64.21000000000004
  label: 7
  w: 47.83999999999992
  x: 797.5
  y: 529.585
- degree: -4.600000000000023
  h: 72.0
  label: 1
  w: 35.710000000000036
  x: 838.355
  y: 350.7
- degree: -5.199999999999989
  h: 68.0
  label: 1
  w: 40.0
  x: 738.0
  y: 613.98
- degree: -4.600000000000023
  h: 68.0
  label: 12
  w: 51.0
  x: 748.5
  y: 89.0
- degree: -5.100000000000023
  h: 72.66000000000003
  label: 1
  w: 38.370000000000005
  x: 784.7149999999999
  y: 442.16999999999996
- degree: -5.399999999999977
  h: 70.0
  label: 6
  w: 48.16000000000008
  x: 596.74
  y: 464.95
- degree: -5.199999999999989
  h: 65.22999999999996
  label: 15
  w: 40.180000000000064
  x: 925.76
  y: 515.3149999999999
- degree: -4.0
  h: 66.41
  label: 25
  w: 49.81999999999999
  x: 439.53999999999996
  y: 219.53500000000003
- degree: -3.6999999999999886
  h: 68.28000000000003
  label: 25
  w: 50.94
  x: 333.03
  y: 411.97
- degree: -4.399999999999977
  h: 65.0
  label: 25
  w: 46.870000000000005
  x: 359.675
  y: 579.77
- degree: -4.300000000000011
  h: 67.79999999999995
  label: 25
  w: 50.900000000000034
  x: 321.46000000000004
  y: 324.25
- degree: -4.0
  h: 67.00000000000006
  label: 12
  w: 41.57000000000005
  x: 408.435
  y: 491.96000000000004
- degree: -5.600000000000023
  h: 61.440000000000055
  label: 12
  w: 45.19
  x: 418.495
  y: 574.11
- degree: -3.8999999999999773
  h: 69.0
  label: 12
  w: 47.10000000000002
  x: 390.43
  y: 317.15
- degree: -3.6999999999999886
  h: 68.0
  label: 11
  w: 48.60000000000002
  x: 452.69
  y: 308.66
- degree: -5.300000000000011
  h: 67.0
  label: 4
  w: 51.0
  x: 859.5
  y: 520.5
- degree: -6.699999999999989
  h: 69.0
  label: 1
  w: 32.389999999999986
  x: 540.835
  y: 556.51
- degree: -5.199999999999989
  h: 68.0
  label: 1
  w: 41.0
  x: 730.04
  y: 537.1
- degree: -2.6999999999999886
  h: 66.0
  label: 11
  w: 48.27999999999997
  x: 905.76
  y: 345.16
- degree: -4.600000000000023
  h: 66.0
  label: 11
  w: 47.799999999999955
  x: 917.09
  y: 430.75
- degree: -3.0
  h: 71.0
  label: 7
  w: 50.0
  x: 715.0
  y: 365.52
- degree: -4.800000000000011
  h: 68.95999999999998
  label: 2
  w: 44.92000000000007
  x: 726.86
  y: 450.27
- degree: -5.199999999999989
  h: 65.64999999999998
  label: 11
  w: 50.74000000000001
  x: 481.06
  y: 565.4549999999999
- degree: -6.5
  h: 70.0
  label: 0
  w: 50.700000000000045
  x: 671.63
  y: 540.64
- degree: -3.6000000000000227
  h: 66.0
  label: 10
  w: 55.0
  x: 760.5
  y: 180.0
- degree: -6.0
  h: 73.0
  label: 0
  w: 48.729999999999905
  x: 661.565
  y: 459.62
- degree: -4.800000000000011
  h: 73.0
  label: 0
  w: 55.0
  x: 491.5
  y: 115.5
- degree: -5.300000000000011
  h: 73.0
  label: 7
  w: 51.0
  x: 586.01
  y: 381.99
- degree: -3.8999999999999773
  h: 75.0
  label: 8
  w: 48.799999999999955
  x: 578.6
  y: 291.36
- degree: -5.5
  h: 75.0
  label: 0
  w: 52.10000000000002
  x: 652.9300000000001
  y: 373.17
- degree: -4.899999999999977
  h: 71.20000000000002
  label: 9
  w: 51.299999999999955
  x: 627.66
  y: 193.76999999999998
- degree: -6.399999999999977
  h: 68.26999999999998
  label: 8
  w: 48.58000000000004
  x: 607.53
  y: 549.245
- degree: -4.199999999999989
  h: 57.860000000000014
  label: 25
  w: 46.920000000000016
  x: 347.35
  y: 496.8
- degree: -6.100000000000023
  h: 67.79999999999998
  label: 4
  w: 49.700000000000045
  x: 618.98
  y: 100.27
- degree: -4.699999999999989
  h: 70.0
  label: 1
  w: 41.39999999999998
  x: 561.7
  y: 201.11
- degree: -4.5
  h: 72.69999999999999
  label: 0
  w: 53.39999999999998
  x: 500.71999999999997
  y: 209.75
- degree: -5.399999999999977
  h: 62.349999999999966
  label: 11
  w: 48.00999999999999
  x: 469.545
  y: 483.755

**Comment by jameslai-dev** [comment]
Hi @yjoh-autonics,

Oops! I'm sorry, the script should be:

``` python
from tqdm import tqdm
from yoro.datasets import RBoxSample

# Load dataset
dataset = RBoxSample(
    image_dir='~/dataset/coating/valid',
    names_file='~/dataset/coating/coating.names'
)

# Check for annotations
for sample_idx, (image, anno) in enumerate(tqdm(dataset, desc='Checking annotation')):
    for idx, inst in enumerate(anno):
        valid = (
            (inst['x'] >= 0 and inst['x'] < image.width) and
            (inst['y'] >= 0 and inst['y'] < image.height)
        )
        if not valid:
            image_path = dataset.instList[sample_idx]['file']
            print(f'Annotation {idx} is not valid for image {image_path}')
```

There is a mistake in getting `image_path`. It should be `sample_idx` instead of `idx`.
Please have a try!

**Comment by ghost** [comment]
I posted a late reply because I was learning.
It works well :)
Thank your answer!
